#!/urs/bin/env bash
# Define variables for the load balancer and web server IP
# Define function to get the DNS record type and destination for subdomain
# Parse commandline arguments


get_domain_info () {
  subdomain = $(dig "$1"."$2" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')

echo "$2 $subdomain" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}


if [ "$#" == 1 ]; then
  get_domain_info "$1" "www"
  get_domain_info "$1" "1b-01"
  get_domain_info "$1" "web-01"
  get_domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
  get_domain_info "$1" "$2"
fi

