#!/urs/bin/env bash
# Define variables for the load balancer and web server IP
# Define function to get the DNS record type and destinati    on for subdomain
# Parse commandline arguments

LB_IP = "01.example.com"
WEB_01_IP = "web-01.example.com"
WEB_02_IP = "web-02.example.com"

get_domain_info () {
  subdomain = $1
  record_type = $(dig +short $subdomain.$domain | awk 'NR==1 {print $2}')
  destination = $(dig +short $subdomain.$domain | awk 'NR==1 {print $1}')
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain = $1
subdomain = $2

if [ -z "$subdomain" ]; then
  get_domain_info "www"
  get_domain_info "1b-01"
  get_domain_info "web-01"
  get_domain_info "web-02"
else
  get_domain_info "$subdomain"
fi

