#!/usr/bin/env bash
# Check if at least 4 parameters are provided
# Transfer the file using scp

if [ $# -lt 4 ] 
then
   echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

